# Generated by Django 4.0.4 on 2022-05-31 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bytes', models.IntegerField(default=0)),
                ('total_bytes', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('intern_quantity', models.IntegerField(default=0)),
                ('junior_quantity', models.IntegerField(default=0)),
                ('middle_quantity', models.IntegerField(default=0)),
                ('senior_quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
    ]
